config/routes.rb
Rails.application.routes.draw do
  # get 'messages/show'
  # get 'messages/index'
  # get 'messages/edit'
  # get 'messages/new'
  # get 'pages/home'

  mount ActionCable.server => '/cable'
  resources :messages ,:groups
  root "pages#home"
  devise_for :users
  get "user/group_message", to: "users#group_message"
  resources :users, only: [:show ,]
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :messages , through: :users
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :sender, class_name: "User",foreign_key: "sender_id"
    belongs_to :receiver, class_name: "User",foreign_key: "receiver_id" , optional: true  
    belongs_to :group, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
mount_uploader :user_image, ImageUploader
    has_and_belongs_to_many :groups
  has_many :messages

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :join_general_group

  def join_general_group
    group = Group.find_by(group_name: "jj")
    self.groups << group
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name,:user_image])
  devise_parameter_sanitizer.permit(:account_update, keys: [:user_name,:user_image])
end
    
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find_by(id: params[:id])
    # @messages = Message.where(group_id: params[:id]).and(Group.find_by(id: params[:id]))
    @new_message = Message.new 

    @group_messages = @group.messages.where.not(group_id: 0)

  end
  
  def index
    # @messages = Message.all
    u1 = User.find_by(id: current_user.id)
    @groups = u1.groups
    
  end
  
  def edit
  end
  
  def new
  end

  def create 
    message = Message.new(message_params)
    message.sender_id = current_user.id
    message.save
    if message.save
      ActionCable.server.broadcast 'messages',
      message: message.body,
      user: message.user.user_name
      head :ok
    end
    redirect_to request.referer
    # raise
  end

  private
  def message_params
    params.require(:message).permit(:user_id,:group_id,:body)
  end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
  end
  
  def index
    @users = User.all
  end
  
  def edit
  end
  
  def new
    # @messages = Message.all
    @message = Message.new 
  end

  def create 
    message = Message.new(message_params)
    message.sender_id = current_user.id
    message.save
    if message.save
      ActionCable.server.broadcast 'messages',
      message: message.body,
      user: message.user.user_name
      head :ok
    end
    # redirect_to request.referer
    # raise
  end

  private
  def message_params
    params.require(:message).permit(:user_id,:receiver_id,:group_id,:body)
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    @messages = Message.where(sender_id: current_user.id, receiver_id: params[:id]).or(Message.where(sender_id: params[:id],receiver_id:current_user.id))
    @message = Message.new
  end

  def group_message
    @user = User.find_by(id: current_user.id)
    # @messages = Message. 

  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_for @message, remote: true do |f| %>
<%= f.text_area :body %>
<%= hidden_field_tag "message[group_id]", params[:id] %>
<%= hidden_field_tag "message[user_id]", current_user.id %>
<%= f.submit %>
<% end %>

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<h1>Groups#index</h1>

<% @groups.each do |group| %>
  <%= link_to group.group_name, group_path(group) %>
  <%# <%= group.users.to_json %>
<% end %>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<% @messages.each do |message| %>
<%# <% if message.user.user_name == ""%> 
<%# <%= message.user_user %>
<%# <%else %>
<%= message.user.user_name %>:
<%# <%end %>
  <%= message.body %>
  <br>
<% end %>

<%= render partial: 'form' %>

app/views/groups/show.html.erb
<h1>Groups#show</h1>

<div class="messages">

<% @group_messages.each do |message| %>
  
  <%# <%=  messege.body %> 
  <div class="mess">
  <img src=<%= cl_image_tag message.user.user_image %> alt="">
  <p class="name-left"><%= message.user.user_name %>:</p>
  <p><%= message.body %></p>
</div>

<% end %>
</div>

<%= form_for @new_message, remote: true do |f| %>
<%= f.text_area :body %>
<%= hidden_field_tag "message[group_id]", params[:id] %>
<%= hidden_field_tag "message[user_id]", current_user.id %>
<%= f.submit %>
<% end %>

app/views/layouts/_nav.html.erb
 <nav>
    <div class="nav-wrapper"> 
      <%# <a href="#" class="brand-logo center">Logo</a> %>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
       <% if user_signed_in? %>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Home", root_path %></li>
        <%else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <%end %>
      </ul>
    </div>
  </nav>

  

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <!-- Page Layout here -->
<%= render partial: 'layouts/nav' %>
    
    </div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  
<div class = "container">

    <%= yield %>
</div>

    <center>
    <a class='dropdown-trigger btn' href='#' data-target='dropdown1'>Drop Me!</a>

  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider" tabindex="-1"></li>
    <li><a href="#!">three</a></li>
    <li><a href="#!"><i class="material-icons">view_module</i>four</a></li>
    <li><a href="#!"><i class="material-icons">cloud</i>five</a></li>
  </ul>
    </center>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message, remote: true do |f| %>
<div class="row">
<div class="col s10">
<%= f.text_area :body ,class:"col 10s" %>
</div>
<%= hidden_field_tag "message[receiver_id]", params[:id] %>
<%= hidden_field_tag "message[user_id]", current_user.id %>

<div class="col s2">
<%= f.submit class:"col 2s" %>
</div>
<% end %>

</div>

app/views/messages/edit.html.erb
<h1>Messages#edit</h1>
<p>Find me in app/views/messages/edit.html.erb</p>

app/views/messages/index.html.erb
<h2>Private Messages</h2>

<% if user_signed_in? %>
<div class="col s3">
<% @users.each do |user| %> 

  <ul class="collection">
    <li class="collection-item"><%= link_to user.email, user_path(user) %></li>
  </ul> 

<% end %> 
</div>
<% end %> 

app/views/messages/new.html.erb
<h1>Messages#new</h1>

app/views/pages/home.html.erb
<h2>Pages</h2>
<% if user_signed_in? %>
<%# <% @users.each do |user| %> 
<%# <div> %>
  <%# <%= link_to user.email, new_message_path(user) %>
<%# </div> %>
<%# <% end %>

<div class="section">
    <h5><%= link_to 'Main group', groups_path()%></h5>
    <p>Stuff</p>
</div>
<div class="divider"></div>
<div class="section">
    <h5><%= link_to 'Private Messages', messages_path()%></h5>
    <p>Stuff</p>
</div>
<div class="divider"></div>
<%# <%= link_to 'Main group', groups_path()%>
<%# <%= link_to 'private', messages_path()%>  

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<p><%= @user.to_json %></p>
<p><%= current_user.to_json %></p>

<%# <p><%= @messages.to_json</p> %>

<% @messages.each do |message| %>

<div class="mess" id="messages">
  <%= cl_image_tag message.user.user_image %>
  <p class="name-left"><%= message.user.user_name %>:</p>
  <p><%= message.body %></p>
</div>

<% end %>
<%= render partial: 'messages/form' %>